language: ruby
rvm:
  - 2.0
  - 2.1

env:
  - "RAILS_VERSION=4-0-stable"
  - "RAILS_VERSION=4-1-stable"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"

notifications:
  email: false
