language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
env:
  - "RAILS_BRANCH=4-1-stable"
  - "RAILS_BRANCH=4-2-stable"
  - "RAILS_BRANCH=5-0-stable"
  - "RAILS_BRANCH=5-1-stable"
  - "RAILS_BRANCH=master"
branches:
  only:
    - master
matrix:
  allow_failures:
    - env: "RAILS_BRANCH=master"
notifications:
  email: false
sudo: false
